"""Wrap generated functions in guest-stack balance checks.

Every lifted function is supposed to leave the guest esp exactly where a real
`ret`/`ret N` would: 4 bytes (the return slot) plus its stdcall argument bytes
above the esp it was entered with. A function that misses (a dropped
fall-through, a mis-sized kernel call, an x87 helper the lifter got wrong)
shifts every esp-relative access in its callers -- functions without a frame
pointer then read their arguments from the wrong slots, which is how D3D's
CreateDevice ended up with a garbage presentation-parameters pointer on 3.1.

For each function in the chosen address ranges whose `ret` instructions all
agree on N, this renames the generated definition `sub_X` to `sub_X_gen` and
emits a wrapper `sub_X` (gen/recomp_probes.c) that calls it and reports a
mismatch through esp_probe_report() (recomp_manual.c). Functions whose rets
disagree, or that never return, are left alone.

Usage (from doa3/, with DOA3_XBE set), after tools.recomp.postprocess:
  py -3 -m tools.recomp.esp_probes [lo-hi ...]      e.g. 0x18B000-0x1EB000
With no ranges: every function in the image.
  py -3 -m tools.recomp.esp_probes --remove         undo
"""
import glob
import json
import os
import re
import sys

from capstone import CS_ARCH_X86, CS_MODE_32, Cs

sys.path.insert(0, os.getcwd())
from tools import xbe_layout as L  # noqa: E402

GEN = os.path.join("src", "game", "recomp", "gen")
OUT = os.path.join(GEN, "recomp_probes.c")
FUNCS = os.path.join("tools", "disasm", "output", "functions.json")
SKIP = {L.SEH_PROLOG, L.SEH_EPILOG, L.FTOL2}


def gen_files():
    return [f for f in sorted(glob.glob(os.path.join(GEN, "recomp_*.c")))
            if os.path.basename(f) not in ("recomp_probes.c", "recomp_dispatch.c")]


def remove():
    n = 0
    for f in gen_files():
        s = open(f).read()
        from tools.recomp.apply_overrides import override_list
        keep = override_list()
        k = 0

        def unren(m):
            nonlocal k
            if int(m.group(1)[4:], 16) in keep:
                return m.group(0)
            k += 1
            return f"void {m.group(1)}(void)"
        s2 = re.sub(r"^void (sub_[0-9A-F]{8})_gen\(void\)$", unren, s, flags=re.M)
        if k:
            open(f, "w").write(s2)
            n += k
    if os.path.exists(OUT):
        open(OUT, "w").write("/* no probes */\n")
    print(f"removed {n} probes", file=sys.stderr)


def main():
    if "--remove" in sys.argv:
        remove()
        return
    ranges = []
    for a in sys.argv[1:]:
        lo, hi = a.split("-")
        ranges.append((int(lo, 16), int(hi, 16)))
    if not ranges:
        ranges = [(0, 0xFFFFFFFF)]

    data = open(L.XBE_PATH, "rb").read()
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    secs = [s for s in L.LAYOUT["sections"] if s[0] not in L.DATA_SECTION_NAMES]

    def code(va, size):
        for s in secs:
            if s[1] <= va < s[1] + s[4]:
                o = s[3] + va - s[1]
                return data[o:o + size]
        return b""

    from tools.recomp.apply_overrides import override_list
    overridden = override_list()     # hand-written; they own the sub_X name
    funcs = json.load(open(FUNCS))
    want = {}
    for f in funcs:
        start, end = int(f["start"], 16), int(f["end"], 16)
        if start in SKIP or start in overridden or not any(lo <= start < hi for lo, hi in ranges):
            continue
        # Only real entries: a seeded fragment (link_seed) starts mid-function
        # and legitimately pops what its function pushed.
        if f.get("detection_method") == "link_seed":
            continue
        rets = set()
        seh = False
        for ins in md.disasm(code(start, end - start), start):
            if ins.mnemonic in ("ret", "retn"):
                rets.add(int(ins.op_str, 0) if ins.op_str else 0)
            elif ins.mnemonic == "call" and ins.op_str.startswith("0x") and \
                    int(ins.op_str, 16) in (L.SEH_PROLOG, L.SEH_EPILOG):
                seh = True      # frame set up / torn down by the SEH helpers
        if seh:
            continue
        if len(rets) == 1:
            want[start] = rets.pop()

    # Rename definitions (only those actually emitted).
    have = {}
    for f in gen_files():
        s = open(f).read()

        def ren(m):
            va = int(m.group(1)[4:], 16)
            if va in want:
                have[va] = want[va]
                return f"void {m.group(1)}_gen(void)"
            return m.group(0)
        s2 = re.sub(r"^void (sub_[0-9A-F]{8})\(void\)$", ren, s, flags=re.M)
        # already-probed definitions stay probed
        for m in re.finditer(r"^void (sub_[0-9A-F]{8})_gen\(void\)$", s2, flags=re.M):
            va = int(m.group(1)[4:], 16)
            if va in want:
                have[va] = want[va]
        if s2 != s:
            open(f, "w").write(s2)

    lines = ["/* Generated by tools/recomp/esp_probes.py: guest-stack balance checks.",
             " * Each wrapper calls the lifted body and reports when esp does not end",
             " * 4 + N bytes above where it started (N from the function's `ret N`). */",
             "#include \"recomp_types.h\"",
             "void esp_probe_report(uint32_t va, uint32_t esp_in, uint32_t esp_out, uint32_t expect);",
             "#define P(va, n) void sub_##va##_gen(void); void sub_##va(void) { \\",
             "    uint32_t e0 = g_esp; sub_##va##_gen(); \\",
             "    if (g_esp - e0 != 4u + (n)) esp_probe_report(0x##va##u, e0, g_esp, 4u + (n)); }"]
    for va in sorted(have):
        lines.append(f"P({va:08X}, {have[va]})")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"{len(have)} functions probed ({len(want)} eligible in range)", file=sys.stderr)


if __name__ == "__main__":
    main()
